apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: apache
  name: apache
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: httpd:latest
      name: latest
      referencePolicy:
        type: ""
