apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: apache
  name: apache
spec:
  replicas: 1
  selector:
    io.kompose.service: apache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: apache
    spec:
      containers:
        - image: ' '
          name: my-apache-app
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: apache-claim0
      restartPolicy: Always
      volumes:
        - name: apache-claim0
          persistentVolumeClaim:
            claimName: apache-claim0
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - my-apache-app
        from:
          kind: ImageStreamTag
          name: apache:latest
      type: ImageChange
